"""expand password size 5

Revision ID: 41316170e673
Revises: 474294f46433
Create Date: 2021-10-31 20:26:46.822994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41316170e673'
down_revision = '474294f46433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=105), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
