"""delete authenticated col 6

Revision ID: 424c730dac8a
Revises: 41316170e673
Create Date: 2021-10-31 20:27:36.665047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424c730dac8a'
down_revision = '41316170e673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
